

import type { Surah } from './types';

export const duas: {
  categoryName: string;
  title: string;
  arabicText: string;
  translation: string;
  phonetic: string;
  audioUrl?: string;
}[] = [
  // Matin & Soir
  {
    categoryName: 'Matin & Soir',
    title: 'Au réveil',
    arabicText: 'الحَمْـدُ لِلّهِ الَّذِي أَحْـيَانَا بَعْـدَ مَا أَمَاتَـنَا وَإليه النُّـشُور',
    translation: "Toute la louange est à Allah qui nous a donné la vie après nous l'avoir reprise et c'est vers Lui que se fera la résurrection.",
    phonetic: 'Alhamdu lillahil-ladhi ahyana ba`da ma amatana wa ilayhin-nushur.',
    audioUrl: '',
  },
  {
    categoryName: 'Matin & Soir',
    title: 'Protection pour le soir',
    arabicText: 'أَعُوذُ بِكَلِمَاتِ اللهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    translation: "Je cherche protection auprès des paroles parfaites d’Allah contre le mal de ce qu’Il a créé.",
    phonetic: "A'udhu bi-kalimatillahit-tammati min sharri ma khalaq.",
    audioUrl: '',
  },
  // Actions Quotidiennes
  {
    categoryName: 'Actions Quotidiennes',
    title: 'En entrant à la mosquée',
    arabicText: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    translation: "Ô Allah, ouvre-moi les portes de Ta miséricorde.",
    phonetic: 'Allahumma ftah li abwaba rahmatik.',
    audioUrl: '',
  },
  {
    categoryName: 'Actions Quotidiennes',
    title: 'En sortant de la mosquée',
    arabicText: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
    translation: "Ô Allah, je Te demande de Ton immense grâce.",
    phonetic: "Allahumma inni as'aluka min fadlik.",
    audioUrl: '',
  },
  // Repas
  {
    categoryName: 'Repas',
    title: 'Avant de manger',
    arabicText: 'بِسْمِ اللهِ',
    translation: "Au nom d'Allah.",
    phonetic: 'Bismillah.',
    audioUrl: '',
  },
  {
    categoryName: 'Repas',
    title: 'Après avoir mangé',
    arabicText: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",
    translation: "Louange à Allah qui nous a nourris, nous a donné à boire, et a fait de nous des Musulmans.",
    phonetic: "Alhamdu lillahil-ladhi at'amana wa saqana wa ja'alana muslimin.",
    audioUrl: '',
  },
  // Voyage
  {
    categoryName: 'Voyage',
    title: 'Invocation du voyageur',
    arabicText: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ، وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
    translation: "Gloire à Celui qui a mis ceci à notre service alors que nous n'étions pas capables de le dominer. Et c'est vers notre Seigneur que nous retournerons.",
    phonetic: 'Subhanal-ladhi sakhara lana hadha wa ma kunna lahu muqrinin. Wa inna ila Rabbina lamunqalibun.',
    audioUrl: '',
  },
  // Sentiments
  {
    categoryName: 'Sentiments',
    title: 'En cas de détresse',
    arabicText: 'لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ',
    translation: "Il n'y a de divinité digne d'adoration que Toi. Gloire à Toi ! J'ai été vraiment du nombre des injustes.",
    phonetic: "La ilaha illa Anta subhanaka inni kuntu min adh-dhalimin.",
    audioUrl: '',
  },
  // Pardon
  {
    categoryName: 'Pardon',
    title: 'Demande de Pardon (Nuit du Destin)',
    arabicText: "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي",
    translation: "Ô Allah, Tu es Pardonneur, et Tu aimes le pardon, alors pardonne-moi.",
    phonetic: "Allahumma Innaka 'Afuwwun Tuhibbul 'Afwa Fa'fu 'Anni.",
    audioUrl: '',
  },
  // Famille
  {
    categoryName: 'Famille',
    title: 'Pour les parents',
    arabicText: 'رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    translation: "Ô mon Seigneur, fais-leur, à tous deux, miséricorde comme ils m'ont élevé tout petit.",
    phonetic: "Rabbi rhamhuma kama rabbayani saghira.",
    audioUrl: '',
  }
];

export const reminders = [
    { "day_id": 1, "title": { "fr": "Confiance", "ar": "الثقة", "en": "Trust" }, "content": { "fr": "Et quiconque place sa confiance en Allah, Il lui suffit.", "ar": "وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ", "en": "And whoever relies upon Allah - then He is sufficient for him." }, "source": "Coran (65:3)" },
    { "day_id": 2, "title": { "fr": "Gratitude", "ar": "الامتنان", "en": "Gratitude" }, "content": { "fr": "Si vous êtes reconnaissants, J'augmenterai Mes bienfaits.", "ar": "لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ", "en": "If you are grateful, I will surely increase you [in favor]." }, "source": "Coran (14:7)" },
    { "day_id": 3, "title": { "fr": "Douceur", "ar": "الرفق", "en": "Gentleness" }, "content": { "fr": "La douceur n'est présente dans une chose que pour l'embellir.", "ar": "إِنَّ الرِّفْقَ لاَ يَكُونُ فِي شَىْءٍ إِلاَّ زَانَهُ", "en": "Gentleness is not in something except that it adorns it." }, "source": "Hadith (Muslim)" },
    { "day_id": 4, "title": { "fr": "Patience", "ar": "الصبر", "en": "Patience" }, "content": { "fr": "L'endurance est une lumière éclatante.", "ar": "الصَّبْرُ ضِيَاءٌ", "en": "Patience is a shining light." }, "source": "Hadith (Muslim)" },
    { "day_id": 5, "title": { "fr": "Facilité", "ar": "اليسر", "en": "Ease" }, "content": { "fr": "À côté de la difficulté est, certes, une facilité.", "ar": "فَإِنَّ مَعَ الْعُسْرِ يُسْرًا", "en": "For indeed, with hardship [will be] ease." }, "source": "Coran (94:5)" },
    { "day_id": 6, "title": { "fr": "Intention", "ar": "النية", "en": "Intention" }, "content": { "fr": "Les actions ne valent que par les intentions.", "ar": "إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ", "en": "Actions are but by intentions." }, "source": "Hadith (Bukhari)" },
    { "day_id": 7, "title": { "fr": "Paix", "ar": "السلام", "en": "Peace" }, "content": { "fr": "N'est-ce pas par le rappel d'Allah que les cœurs s'apaisent ?", "ar": "أَلاَ بِذِكْرِ اللّهِ تَطْمَئِنُّ الْقُلُوبُ", "en": "Unquestionably, by the remembrance of Allah hearts are assured." }, "source": "Coran (13:28)" },
    { "day_id": 8, "title": { "fr": "Bonté", "ar": "الإحسان", "en": "Goodness" }, "content": { "fr": "Le meilleur d'entre vous est celui qui est le meilleur avec sa famille.", "ar": "خَيْرُكُمْ خَيْرُكُمْ لِأَهْلِهِ", "en": "The best of you is the one who is best to his family." }, "source": "Hadith (Tirmidhi)" },
    { "day_id": 9, "title": { "fr": "Sagesse", "ar": "الحكمة", "en": "Wisdom" }, "content": { "fr": "Il donne la sagesse à qui Il veut. Et quiconque reçoit la sagesse, a certes reçu un bien immense.", "ar": "يُؤتِي الْحِكْمَةَ مَن يَشَاء وَمَن يُؤْتَ الْحِكْمَةَ فَقَدْ أُوتِيَ خَيْرًا كَثِيرًا", "en": "He gives wisdom to whom He wills, and whoever has been given wisdom has certainly been given much good." }, "source": "Coran (2:269)" },
    { "day_id": 10, "title": { "fr": "Charité", "ar": "الصدقة", "en": "Charity" }, "content": { "fr": "Ceux qui dépensent leurs biens dans le sentier d’Allah... leur récompense est auprès de leur Seigneur.", "ar": "الَّذِينَ يُنفِقُونَ أَمْوَالَهُمْ فِي سَبِيلِ اللّهِ ... لَهُمْ أَجْرُهُمْ عِندَ رَبِّهِمْ", "en": "Those who spend their wealth in the way of Allah... will have their reward with their Lord." }, "source": "Coran (2:262)" },
    { "day_id": 11, "title": { "fr": "Modestie", "ar": "الحياء", "en": "Modesty" }, "content": { "fr": "La modestie fait partie de la foi.", "ar": "الْحَيَاءُ مِنَ الإِيمَانِ", "en": "Modesty is part of faith." }, "source": "Hadith (Bukhari)" },
    { "day_id": 12, "title": { "fr": "Unicité", "ar": "التوحيد", "en": "Oneness" }, "content": { "fr": "Dis: 'Il est Allah, Unique'.", "ar": "قُلْ هُوَ اللَّهُ أَحَدٌ", "en": "Say, 'He is Allah, [who is] One'." }, "source": "Coran (112:1)" },
    { "day_id": 13, "title": { "fr": "Miséricorde", "ar": "الرحمة", "en": "Mercy" }, "content": { "fr": "Ma miséricorde embrasse toute chose.", "ar": "وَرَحْمَتِي وَسِعَتْ كُلَّ شَيْءٍ", "en": "My mercy encompasses all things." }, "source": "Coran (7:156)" },
    { "day_id": 14, "title": { "fr": "Le meilleur des hommes", "ar": "خير الناس", "en": "The best of people" }, "content": { "fr": "Le meilleur d'entre vous est celui qui est le meilleur avec sa famille.", "ar": "خَيْرُكُمْ خَيْرُكُمْ لِأَهْلِهِ", "en": "The best of you is the one who is best to his family." }, "source": "Hadith (Tirmidhi)" },
    { "day_id": 15, "title": { "fr": "Le sourire", "ar": "الابتسامة", "en": "The smile" }, "content": { "fr": "Sourire à ton frère est une aumône.", "ar": "تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ", "en": "Your smiling in the face of your brother is charity." }, "source": "Hadith (Tirmidhi)" },
    { "day_id": 16, "title": { "fr": "La quête du savoir", "ar": "طلب العلم", "en": "Seeking knowledge" }, "content": { "fr": "Quiconque prend un chemin pour rechercher la connaissance, Allah lui facilite un chemin vers le Paradis.", "ar": "مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ طَرِيقًا إِلَى الْجَنَّةِ", "en": "Whoever takes a path in search of knowledge, Allah makes the path to Paradise easy for him." }, "source": "Hadith (Muslim)" },
    { "day_id": 17, "title": { "fr": "La parole", "ar": "الكلام", "en": "Speech" }, "content": { "fr": "Quiconque croit en Allah et au Jour dernier, qu'il dise du bien ou qu'il se taise.", "ar": "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ", "en": "Whoever believes in Allah and the Last Day, let him speak good or remain silent." }, "source": "Hadith (Bukhari)" },
    { "day_id": 18, "title": { "fr": "L'épreuve", "ar": "الابتلاء", "en": "The trial" }, "content": { "fr": "Allah n'impose à aucune âme une charge supérieure à sa capacité.", "ar": "لاَ يُكَلِّفُ اللّهُ نَفْسًا إِلاَّ وُسْعَهَا", "en": "Allah does not burden a soul beyond that it can bear." }, "source": "Coran (2:286)" },
    { "day_id": 19, "title": { "fr": "L'humilité", "ar": "التواضع", "en": "Humility" }, "content": { "fr": "Et les serviteurs du Tout Miséricordieux sont ceux qui marchent sur la terre humblement.", "ar": "وَعِبَادُ الرَّحْمَنِ الَّذِينَ يَمْشُونَ عَلَى الْأَرْضِ هَوْنًا", "en": "And the servants of the Most Merciful are those who walk upon the earth easily." }, "source": "Coran (25:63)" },
    { "day_id": 20, "title": { "fr": "L'invocation", "ar": "الدعاء", "en": "The supplication" }, "content": { "fr": "Et votre Seigneur dit: 'Invoquez-Moi, Je vous répondrai.'", "ar": "وَقَالَ رَبُّكُمُ ادْعُونِي أَسْتَجِبْ لَكُمْ", "en": "And your Lord says, 'Call upon Me; I will respond to you'." }, "source": "Coran (40:60)" },
    { "day_id": 21, "title": { "fr": "La propreté", "ar": "النظافة", "en": "Cleanliness" }, "content": { "fr": "La propreté est la moitié de la foi.", "ar": "الطَّهُورُ شَطْرُ الإِيمَانِ", "en": "Cleanliness is half of faith." }, "source": "Hadith (Muslim)" },
    { "day_id": 22, "title": { "fr": "La fraternité", "ar": "الأخوة", "en": "Brotherhood" }, "content": { "fr": "Les croyants ne sont que des frères.", "ar": "إِنَّمَا الْمُؤْمِنُونَ إِخْوَةٌ", "en": "The believers are but brothers." }, "source": "Coran (49:10)" },
    { "day_id": 23, "title": { "fr": "Ne pas se nuire", "ar": "لا ضرر ولا ضرار", "en": "Do not harm" }, "content": { "fr": "Ne vous nuisez pas les uns aux autres.", "ar": "لاَ ضَرَرَ وَلاَ ضِرَارَ", "en": "There should be neither harming nor reciprocating harm." }, "source": "Hadith (Ibn Majah)" },
    { "day_id": 24, "title": { "fr": "L'optimisme", "ar": "التفاؤل", "en": "Optimism" }, "content": { "fr": "Et ne désespérez pas de la miséricorde d'Allah.", "ar": "وَلاَ تَيْأَسُواْ مِن رَّوْحِ اللّهِ", "en": "And do not despair of relief from Allah." }, "source": "Coran (12:87)" },
    { "day_id": 25, "title": { "fr": "La bonne action", "ar": "الحسنة", "en": "The good deed" }, "content": { "fr": "Les bonnes actions effacent les mauvaises.", "ar": "إِنَّ الْحَسَنَاتِ يُذْهِبْنَ السَّيِّئَاتِ", "en": "Indeed, good deeds do away with misdeeds." }, "source": "Coran (11:114)" },
    { "day_id": 26, "title": { "fr": "La générosité", "ar": "الكرم", "en": "Generosity" }, "content": { "fr": "Celui qui est généreux est proche d'Allah, proche des gens, proche du Paradis.", "ar": "السَّخِيُّ قَرِيبٌ مِنَ اللَّهِ قَرِيبٌ مِنَ الْجَنَّةِ قَرِيبٌ مِنَ النَّاسِ", "en": "The generous person is close to Allah, close to Paradise, close to the people." }, "source": "Hadith (Tirmidhi)" },
    { "day_id": 27, "title": { "fr": "Le rappel", "ar": "الذكر", "en": "The remembrance" }, "content": { "fr": "Et rappelle, car le rappel profite aux croyants.", "ar": "وَذَكِّرْ فَإِنَّ الذِّكْرَى تَنفَعُ الْمُؤْمِنِينَ", "en": "And remind, for indeed, the reminder benefits the believers." }, "source": "Coran (51:55)" },
    { "day_id": 28, "title": { "fr": "La justice", "ar": "العدل", "en": "Justice" }, "content": { "fr": "Soyez justes, cela est plus proche de la piété.", "ar": "اعْدِلُواْ هُوَ أَقْرَبُ لِلتَّقْوَى", "en": "Be just; that is nearer to righteousness." }, "source": "Coran (5:8)" },
    { "day_id": 29, "title": { "fr": "La méditation", "ar": "التأمل", "en": "Meditation" }, "content": { "fr": "Dans la création des cieux et de la terre... il y a certes des signes pour les doués d'intelligence.", "ar": "إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالأَرْضِ ... لآيَاتٍ لِّأُوْلِي الألْبَابِ", "en": "Indeed, in the creation of the heavens and the earth...are signs for those of understanding." }, "source": "Coran (3:190)" },
    { "day_id": 30, "title": { "fr": "La finalité", "ar": "الغاية", "en": "The end" }, "content": { "fr": "Et vers ton Seigneur est le retour final.", "ar": "إِلَى رَبِّكَ الرُّجْعَى", "en": "To your Lord is the return." }, "source": "Coran (96:8)" }
];

// Note: This is a placeholder for the full Quran data.
// In a real application, this would be populated from a full data source.
// For now, only the first two surahs have verse data.
export const quran: Surah[] = [
  {
    number: 1,
    nameAr: 'الفاتحة',
    nameFr: 'Al-Fatiha',
    revelation: 'Meccan',
    versesCount: 7,
    verses: [
      {
        number: 1,
        textAr: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
        textFr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux.",
      },
      {
        number: 2,
        textAr: 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ',
        textFr: "Louange à Allah, Seigneur de l'univers.",
      },
      {
        number: 3,
        textAr: 'الرَّحْمَٰنِ الرَّحِيمِ',
        textFr: 'Le Tout Miséricordieux, le Très Miséricordieux.',
      },
      {
        number: 4,
        textAr: 'مَالِكِ يَوْمِ الدِّينِ',
        textFr: 'Maître du Jour de la rétribution.',
      },
      {
        number: 5,
        textAr: 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
        textFr:
          "C'est Toi [Seul] que nous adorons, et c'est Toi [Seul] dont nous implorons secours.",
      },
      {
        number: 6,
        textAr: 'اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ',
        textFr: 'Guide-nous dans le droit chemin,',
      },
      {
        number: 7,
        textAr:
          'صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',
        textFr:
          'le chemin de ceux que Tu as comblés de faveurs, non pas de ceux qui ont encouru Ta colère, ni des égarés.',
      },
    ],
  },
  {
    number: 2,
    nameAr: 'البقرة',
    nameFr: 'Al-Baqara',
    revelation: 'Medinan',
    versesCount: 286,
    verses: [],
  },
  {
    number: 3,
    nameAr: 'آل عمران',
    nameFr: 'Al-Imran',
    revelation: 'Medinan',
    versesCount: 200,
    verses: [],
  },
  {
    number: 4,
    nameAr: 'النساء',
    nameFr: 'An-Nisa',
    revelation: 'Medinan',
    versesCount: 176,
    verses: [],
  },
  {
    number: 5,
    nameAr: 'المائدة',
    nameFr: 'Al-Maidah',
    revelation: 'Medinan',
    versesCount: 120,
    verses: [],
  },
  {
    number: 6,
    nameAr: 'الأنعام',
    nameFr: 'Al-Anam',
    revelation: 'Meccan',
    versesCount: 165,
    verses: [],
  },
  {
    number: 7,
    nameAr: 'الأعراف',
    nameFr: 'Al-Araf',
    revelation: 'Meccan',
    versesCount: 206,
    verses: [],
  },
  {
    number: 8,
    nameAr: 'الأنفال',
    nameFr: 'Al-Anfal',
    revelation: 'Medinan',
    versesCount: 75,
    verses: [],
  },
  {
    number: 9,
    nameAr: 'التوبة',
    nameFr: 'At-Tawbah',
    revelation: 'Medinan',
    versesCount: 129,
    verses: [],
  },
  {
    number: 10,
    nameAr: 'يونس',
    nameFr: 'Yunus',
    revelation: 'Meccan',
    versesCount: 109,
    verses: [],
  },
  {
    number: 11,
    nameAr: 'هود',
    nameFr: 'Hud',
    revelation: 'Meccan',
    versesCount: 123,
    verses: [],
  },
  {
    number: 12,
    nameAr: 'يوسف',
    nameFr: 'Yusuf',
    revelation: 'Meccan',
    versesCount: 111,
    verses: [],
  },
  {
    number: 13,
    nameAr: 'الرعد',
    nameFr: 'Ar-Rad',
    revelation: 'Medinan',
    versesCount: 43,
    verses: [],
  },
  {
    number: 14,
    nameAr: 'ابراهيم',
    nameFr: 'Ibrahim',
    revelation: 'Meccan',
    versesCount: 52,
    verses: [],
  },
  {
    number: 15,
    nameAr: 'الحجر',
    nameFr: 'Al-Hijr',
    revelation: 'Meccan',
    versesCount: 99,
    verses: [],
  },
  {
    number: 16,
    nameAr: 'النحل',
    nameFr: 'An-Nahl',
    revelation: 'Meccan',
    versesCount: 128,
    verses: [],
  },
  {
    number: 17,
    nameAr: 'الإسراء',
    nameFr: 'Al-Isra',
    revelation: 'Meccan',
    versesCount: 111,
    verses: [],
  },
  {
    number: 18,
    nameAr: 'الكهف',
    nameFr: 'Al-Kahf',
    revelation: 'Meccan',
    versesCount: 110,
    verses: [],
  },
  {
    number: 19,
    nameAr: 'مريم',
    nameFr: 'Maryam',
    revelation: 'Meccan',
    versesCount: 98,
    verses: [],
  },
  {
    number: 20,
    nameAr: 'طه',
    nameFr: 'Taha',
    revelation: 'Meccan',
    versesCount: 135,
    verses: [],
  },
  {
    number: 21,
    nameAr: 'الأنبياء',
    nameFr: 'Al-Anbiya',
    revelation: 'Meccan',
    versesCount: 112,
    verses: [],
  },
  {
    number: 22,
    nameAr: 'الحج',
    nameFr: 'Al-Hajj',
    revelation: 'Medinan',
    versesCount: 78,
    verses: [],
  },
  {
    number: 23,
    nameAr: 'المؤمنون',
    nameFr: 'Al-Muminun',
    revelation: 'Meccan',
    versesCount: 118,
    verses: [],
  },
  {
    number: 24,
    nameAr: 'النور',
    nameFr: 'An-Nur',
    revelation: 'Medinan',
    versesCount: 64,
    verses: [],
  },
  {
    number: 25,
    nameAr: 'الفرقان',
    nameFr: 'Al-Furqan',
    revelation: 'Meccan',
    versesCount: 77,
    verses: [],
  },
  {
    number: 26,
    nameAr: 'الشعراء',
    nameFr: 'Ash-Shuara',
    revelation: 'Meccan',
    versesCount: 227,
    verses: [],
  },
  {
    number: 27,
    nameAr: 'النمل',
    nameFr: 'An-Naml',
    revelation: 'Meccan',
    versesCount: 93,
    verses: [],
  },
  {
    number: 28,
    nameAr: 'القصص',
    nameFr: 'Al-Qasas',
    revelation: 'Meccan',
    versesCount: 88,
    verses: [],
  },
  {
    number: 29,
    nameAr: 'العنكبوت',
    nameFr: 'Al-Ankabut',
    revelation: 'Meccan',
    versesCount: 69,
    verses: [],
  },
  {
    number: 30,
    nameAr: 'الروم',
    nameFr: 'Ar-Rum',
    revelation: 'Meccan',
    versesCount: 60,
    verses: [],
  },
  {
    number: 31,
    nameAr: 'لقمان',
    nameFr: 'Luqman',
    revelation: 'Meccan',
    versesCount: 34,
    verses: [],
  },
  {
    number: 32,
    nameAr: 'السجدة',
    nameFr: 'As-Sajdah',
    revelation: 'Meccan',
    versesCount: 30,
    verses: [],
  },
  {
    number: 33,
    nameAr: 'الأحزاب',
    nameFr: 'Al-Ahzab',
    revelation: 'Medinan',
    versesCount: 73,
    verses: [],
  },
  {
    number: 34,
    nameAr: 'سبإ',
    nameFr: 'Saba',
    revelation: 'Meccan',
    versesCount: 54,
    verses: [],
  },
  {
    number: 35,
    nameAr: 'فاطر',
    nameFr: 'Fatir',
    revelation: 'Meccan',
    versesCount: 45,
    verses: [],
  },
  {
    number: 36,
    nameAr: 'يس',
    nameFr: 'Ya-Sin',
    revelation: 'Meccan',
    versesCount: 83,
    verses: [],
  },
  {
    number: 37,
    nameAr: 'الصافات',
    nameFr: 'As-Saffat',
    revelation: 'Meccan',
    versesCount: 182,
    verses: [],
  },
  {
    number: 38,
    nameAr: 'ص',
    nameFr: 'Sad',
    revelation: 'Meccan',
    versesCount: 88,
    verses: [],
  },
  {
    number: 39,
    nameAr: 'الزمر',
    nameFr: 'Az-Zumar',
    revelation: 'Meccan',
    versesCount: 75,
    verses: [],
  },
  {
    number: 40,
    nameAr: 'غافر',
    nameFr: 'Ghafir',
    revelation: 'Meccan',
    versesCount: 85,
    verses: [],
  },
  {
    number: 41,
    nameAr: 'فصلت',
    nameFr: 'Fussilat',
    revelation: 'Meccan',
    versesCount: 54,
    verses: [],
  },
  {
    number: 42,
    nameAr: 'الشورى',
    nameFr: 'Ash-Shura',
    revelation: 'Meccan',
    versesCount: 53,
    verses: [],
  },
  {
    number: 43,
    nameAr: 'الزخرف',
    nameFr: 'Az-Zukhruf',
    revelation: 'Meccan',
    versesCount: 89,
    verses: [],
  },
  {
    number: 44,
    nameAr: 'الدخان',
    nameFr: 'Ad-Dukhan',
    revelation: 'Meccan',
    versesCount: 59,
    verses: [],
  },
  {
    number: 45,
    nameAr: 'الجاثية',
    nameFr: 'Al-Jathiyah',
    revelation: 'Meccan',
    versesCount: 37,
    verses: [],
  },
  {
    number: 46,
    nameAr: 'الأحقاف',
    nameFr: 'Al-Ahqaf',
    revelation: 'Meccan',
    versesCount: 35,
    verses: [],
  },
  {
    number: 47,
    nameAr: 'محمد',
    nameFr: 'Muhammad',
    revelation: 'Medinan',
    versesCount: 38,
    verses: [],
  },
  {
    number: 48,
    nameAr: 'الفتح',
    nameFr: 'Al-Fath',
    revelation: 'Medinan',
    versesCount: 29,
    verses: [],
  },
  {
    number: 49,
    nameAr: 'الحجرات',
    nameFr: 'Al-Hujurat',
    revelation: 'Medinan',
    versesCount: 18,
    verses: [],
  },
  {
    number: 50,
    nameAr: 'ق',
    nameFr: 'Qaf',
    revelation: 'Meccan',
    versesCount: 45,
    verses: [],
  },
  {
    number: 51,
    nameAr: 'الذاريات',
    nameFr: 'Adh-Dhariyat',
    revelation: 'Meccan',
    versesCount: 60,
    verses: [],
  },
  {
    number: 52,
    nameAr: 'الطور',
    nameFr: 'At-Tur',
    revelation: 'Meccan',
    versesCount: 49,
    verses: [],
  },
  {
    number: 53,
    nameAr: 'النجم',
    nameFr: 'An-Najm',
    revelation: 'Meccan',
    versesCount: 62,
    verses: [],
  },
  {
    number: 54,
    nameAr: 'القمر',
    nameFr: 'Al-Qamar',
    revelation: 'Meccan',
    versesCount: 55,
    verses: [],
  },
  {
    number: 55,
    nameAr: 'الرحمن',
    nameFr: 'Ar-Rahman',
    revelation: 'Medinan',
    versesCount: 78,
    verses: [],
  },
  {
    number: 56,
    nameAr: 'الواقعة',
    nameFr: 'Al-Waqiah',
    revelation: 'Meccan',
    versesCount: 96,
    verses: [],
  },
  {
    number: 57,
    nameAr: 'الحديد',
    nameFr: 'Al-Hadid',
    revelation: 'Medinan',
    versesCount: 29,
    verses: [],
  },
  {
    number: 58,
    nameAr: 'المجادلة',
    nameFr: 'Al-Mujadilah',
    revelation: 'Medinan',
    versesCount: 22,
    verses: [],
  },
  {
    number: 59,
    nameAr: 'الحشر',
    nameFr: 'Al-Hashr',
    revelation: 'Medinan',
    versesCount: 24,
    verses: [],
  },
  {
    number: 60,
    nameAr: 'الممتحنة',
    nameFr: 'Al-Mumtahanah',
    revelation: 'Medinan',
    versesCount: 13,
    verses: [],
  },
  {
    number: 61,
    nameAr: 'الصف',
    nameFr: 'As-Saff',
    revelation: 'Medinan',
    versesCount: 14,
    verses: [],
  },
  {
    number: 62,
    nameAr: 'الجمعة',
    nameFr: 'Al-Jumuah',
    revelation: 'Medinan',
    versesCount: 11,
    verses: [],
  },
  {
    number: 63,
    nameAr: 'المنافقون',
    nameFr: 'Al-Munafiqun',
    revelation: 'Medinan',
    versesCount: 11,
    verses: [],
  },
  {
    number: 64,
    nameAr: 'التغابن',
    nameFr: 'At-Taghabun',
    revelation: 'Medinan',
    versesCount: 18,
    verses: [],
  },
  {
    number: 65,
    nameAr: 'الطلاق',
    nameFr: 'At-Talaq',
    revelation: 'Medinan',
    versesCount: 12,
    verses: [],
  },
  {
    number: 66,
    nameAr: 'التحريم',
    nameFr: 'At-Tahrim',
    revelation: 'Medinan',
    versesCount: 12,
    verses: [],
  },
  {
    number: 67,
    nameAr: 'الملك',
    nameFr: 'Al-Mulk',
    revelation: 'Meccan',
    versesCount: 30,
    verses: [],
  },
  {
    number: 68,
    nameAr: 'القلم',
    nameFr: 'Al-Qalam',
    revelation: 'Meccan',
    versesCount: 52,
    verses: [],
  },
  {
    number: 69,
    nameAr: 'الحاقة',
    nameFr: 'Al-Haqqah',
    revelation: 'Meccan',
    versesCount: 52,
    verses: [],
  },
  {
    number: 70,
    nameAr: 'المعارج',
    nameFr: 'Al-Maarij',
    revelation: 'Meccan',
    versesCount: 44,
    verses: [],
  },
  {
    number: 71,
    nameAr: 'نوح',
    nameFr: 'Nuh',
    revelation: 'Meccan',
    versesCount: 28,
    verses: [],
  },
  {
    number: 72,
    nameAr: 'الجن',
    nameFr: 'Al-Jinn',
    revelation: 'Meccan',
    versesCount: 28,
    verses: [],
  },
  {
    number: 73,
    nameAr: 'المزمل',
    nameFr: 'Al-Muzzammil',
    revelation: 'Meccan',
    versesCount: 20,
    verses: [],
  },
  {
    number: 74,
    nameAr: 'المدثر',
    nameFr: 'Al-Muddaththir',
    revelation: 'Meccan',
    versesCount: 56,
    verses: [],
  },
  {
    number: 75,
    nameAr: 'القيامة',
    nameFr: 'Al-Qiyamah',
    revelation: 'Meccan',
    versesCount: 40,
    verses: [],
  },
  {
    number: 76,
    nameAr: ' الانسان',
    nameFr: 'Al-Insan',
    revelation: 'Medinan',
    versesCount: 31,
    verses: [],
  },
  {
    number: 77,
    nameAr: 'المرسلات',
    nameFr: 'Al-Mursalat',
    revelation: 'Meccan',
    versesCount: 50,
    verses: [],
  },
  {
    number: 78,
    nameAr: 'النبإ',
    nameFr: 'An-Naba',
    revelation: 'Meccan',
    versesCount: 40,
    verses: [],
  },
  {
    number: 79,
    nameAr: 'النازعات',
    nameFr: 'An-Naziat',
    revelation: 'Meccan',
    versesCount: 46,
    verses: [],
  },
  {
    number: 80,
    nameAr: 'عبس',
    nameFr: 'Abasa',
    revelation: 'Meccan',
    versesCount: 42,
    verses: [],
  },
  {
    number: 81,
    nameAr: 'التكوير',
    nameFr: 'At-Takwir',
    revelation: 'Meccan',
    versesCount: 29,
    verses: [],
  },
  {
    number: 82,
    nameAr: 'الانفطار',
    nameFr: 'Al-Infitar',
    revelation: 'Meccan',
    versesCount: 19,
    verses: [],
  },
  {
    number: 83,
    nameAr: 'المطففين',
    nameFr: 'Al-Mutaffifin',
    revelation: 'Meccan',
    versesCount: 36,
    verses: [],
  },
  {
    number: 84,
    nameAr: 'الانشقاق',
    nameFr: 'Al-Inshiqaq',
    revelation: 'Meccan',
    versesCount: 25,
    verses: [],
  },
  {
    number: 85,
    nameAr: 'البروج',
    nameFr: 'Al-Buruj',
    revelation: 'Meccan',
    versesCount: 22,
    verses: [],
  },
  {
    number: 86,
    nameAr: 'الطارق',
    nameFr: 'At-Tariq',
    revelation: 'Meccan',
    versesCount: 17,
    verses: [],
  },
  {
    number: 87,
    nameAr: 'الأعلى',
    nameFr: 'Al-Ala',
    revelation: 'Meccan',
    versesCount: 19,
    verses: [],
  },
  {
    number: 88,
    nameAr: 'الغاشية',
    nameFr: 'Al-Ghashiyah',
    revelation: 'Meccan',
    versesCount: 26,
    verses: [],
  },
  {
    number: 89,
    nameAr: 'الفجر',
    nameFr: 'Al-Fajr',
    revelation: 'Meccan',
    versesCount: 30,
    verses: [],
  },
  {
    number: 90,
    nameAr: 'البلد',
    nameFr: 'Al-Balad',
    revelation: 'Meccan',
    versesCount: 20,
    verses: [],
  },
  {
    number: 91,
    nameAr: 'الشمس',
    nameFr: 'Ash-Shams',
    revelation: 'Meccan',
    versesCount: 15,
    verses: [],
  },
  {
    number: 92,
    nameAr: 'الليل',
    nameFr: 'Al-Layl',
    revelation: 'Meccan',
    versesCount: 21,
    verses: [],
  },
  {
    number: 93,
    nameAr: 'الضحى',
    nameFr: 'Ad-Duha',
    revelation: 'Meccan',
    versesCount: 11,
    verses: [],
  },
  {
    number: 94,
    nameAr: 'الشرح',
    nameFr: 'Ash-Sharh',
    revelation: 'Meccan',
    versesCount: 8,
    verses: [],
  },
  {
    number: 95,
    nameAr: 'التين',
    nameFr: 'At-Tin',
    revelation: 'Meccan',
    versesCount: 8,
    verses: [],
  },
  {
    number: 96,
    nameAr: 'العلق',
    nameFr: 'Al-Alaq',
    revelation: 'Meccan',
    versesCount: 19,
    verses: [],
  },
  {
    number: 97,
    nameAr: 'القدر',
    nameFr: 'Al-Qadr',
    revelation: 'Meccan',
    versesCount: 5,
    verses: [],
  },
  {
    number: 98,
    nameAr: 'البينة',
    nameFr: 'Al-Bayyinah',
    revelation: 'Medinan',
    versesCount: 8,
    verses: [],
  },
  {
    number: 99,
    nameAr: 'الزلزلة',
    nameFr: 'Az-Zalzalah',
    revelation: 'Medinan',
    versesCount: 8,
    verses: [],
  },
  {
    number: 100,
    nameAr: 'العاديات',
    nameFr: 'Al-Adiyat',
    revelation: 'Meccan',
    versesCount: 11,
    verses: [],
  },
  {
    number: 101,
    nameAr: 'القارعة',
    nameFr: 'Al-Qariah',
    revelation: 'Meccan',
    versesCount: 11,
    verses: [],
  },
  {
    number: 102,
    nameAr: 'التكاثر',
    nameFr: 'At-Takathur',
    revelation: 'Meccan',
    versesCount: 8,
    verses: [],
  },
  {
    number: 103,
    nameAr: 'العصر',
    nameFr: 'Al-Asr',
    revelation: 'Meccan',
    versesCount: 3,
    verses: [],
  },
  {
    number: 104,
    nameAr: 'الهمزة',
    nameFr: 'Al-Humazah',
    revelation: 'Meccan',
    versesCount: 9,
    verses: [],
  },
  {
    number: 105,
    nameAr: 'الفيل',
    nameFr: 'Al-Fil',
    revelation: 'Meccan',
    versesCount: 5,
    verses: [],
  },
  {
    number: 106,
    nameAr: 'قريش',
    nameFr: 'Quraysh',
    revelation: 'Meccan',
    versesCount: 4,
    verses: [],
  },
  {
    number: 107,
    nameAr: 'الماعون',
    nameFr: 'Al-Maun',
    revelation: 'Meccan',
    versesCount: 7,
    verses: [],
  },
  {
    number: 108,
    nameAr: 'الكوثر',
    nameFr: 'Al-Kawthar',
    revelation: 'Meccan',
    versesCount: 3,
    verses: [],
  },
  {
    number: 109,
    nameAr: 'الكافرون',
    nameFr: 'Al-Kafirun',
    revelation: 'Meccan',
    versesCount: 6,
    verses: [],
  },
  {
    number: 110,
    nameAr: 'النصر',
    nameFr: 'An-Nasr',
    revelation: 'Medinan',
    versesCount: 3,
    verses: [],
  },
  {
    number: 111,
    nameAr: 'المسد',
    nameFr: 'Al-Masad',
    revelation: 'Meccan',
    versesCount: 5,
    verses: [],
  },
  {
    number: 112,
    nameAr: 'الإخلاص',
    nameFr: 'Al-Ikhlas',
    revelation: 'Meccan',
    versesCount: 4,
    verses: [
      { number: 1, textAr: 'قُلْ هُوَ اللَّهُ أَحَدٌ', textFr: 'Dis: «Il est Allah, Unique.' },
      { number: 2, textAr: 'اللَّهُ الصَّمَدُ', textFr: 'Allah, Le Seul à être imploré pour ce que nous désirons.' },
      { number: 3, textAr: 'لَمْ يَلِدْ وَلَمْ يُولَدْ', textFr: "Il n'a jamais engendré, n'a pas été engendré non plus." },
      { number: 4, textAr: 'وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ', textFr: "Et nul n'est égal à Lui»." },
    ],
  },
  {
    number: 113,
    nameAr: 'الفلق',
    nameFr: 'Al-Falaq',
    revelation: 'Meccan',
    versesCount: 5,
    verses: [
      { "number": 1, "textAr": "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ", "textFr": "Dis: «Je cherche protection auprès du Seigneur de l'aube naissante," },
      { "number": 2, "textAr": "مِنْ شَرِّ مَا خَلَقَ", "textFr": "contre le mal des êtres qu'Il a créés," },
      { "number": 3, "textAr": "وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ", "textFr": "contre le mal de l'obscurité quand elle s'approfondit," },
      { "number": 4, "textAr": "وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ", "textFr": "contre le mal de celles qui soufflent (les sorcières) sur les nœuds," },
      { "number": 5, "textAr": "وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ", "textFr": "et contre le mal de l'envieux quand il envie»." }
    ],
  },
  {
    number: 114,
    nameAr: 'الناس',
    nameFr: 'An-Nas',
    revelation: 'Meccan',
    versesCount: 6,
    verses: [
        { "number": 1, "textAr": "قُلْ أَعُوذُ بِرَبِّ النَّاسِ", "textFr": "Dis: «Je cherche protection auprès du Seigneur des hommes," },
        { "number": 2, "textAr": "مَلِكِ النَّاسِ", "textFr": "Le Souverain des hommes," },
        { "number": 3, "textAr": "إِلَهِ النَّاسِ", "textFr": "Dieu des hommes," },
        { "number": 4, "textAr": "مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ", "textFr": "contre le mal du mauvais conseiller, furtif," },
        { "number": 5, "textAr": "الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ", "textFr": "qui souffle le mal dans les poitrines des hommes," },
        { "number": 6, "textAr": "مِنَ الْجِنَّةِ وَالنَّاسِ", "textFr": "qu'il soit un djinn ou un être humain»." }
    ],
  },
];
